# Generated by Django 3.2.5 on 2022-05-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_maleshirts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.IntegerField()),
                ('tummy_shape', models.CharField(max_length=20)),
                ('fit_preference', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=5)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
