# Generated by Django 3.2.5 on 2022-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinput',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
