# Generated by Django 3.2.5 on 2022-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usersinput_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=5)),
                ('item', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=5)),
                ('waist', models.IntegerField()),
                ('tummy_shape', models.CharField(max_length=20)),
                ('fit_preference', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('chest', models.IntegerField()),
            ],
        ),
    ]
