# Generated by Django 3.2.5 on 2022-05-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_normtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FemalePants',
        ),
        migrations.DeleteModel(
            name='FemaleShirts',
        ),
        migrations.DeleteModel(
            name='MalePants',
        ),
        migrations.DeleteModel(
            name='MaleShirts',
        ),
    ]
