# Generated by Django 3.2.5 on 2022-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_femalepants_femaleshirts_malepants_maleshirts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normtable',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='normtable',
            name='fit_preference',
        ),
        migrations.RemoveField(
            model_name='normtable',
            name='size',
        ),
        migrations.RemoveField(
            model_name='normtable',
            name='tummy_shape',
        ),
        migrations.AddField(
            model_name='normtable',
            name='brand_ASOS',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normtable',
            name='brand_HM',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normtable',
            name='brand_PULL_BEAR',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normtable',
            name='brand_ZARA',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normtable',
            name='fit_labels',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normtable',
            name='size_labels',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normtable',
            name='tummy_labels',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normtable',
            name='age',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='normtable',
            name='chest',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='normtable',
            name='height',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='normtable',
            name='waist',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='normtable',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
