# Generated by Django 3.2.5 on 2022-05-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220515_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FemalePants',
        ),
        migrations.DeleteModel(
            name='FemaleShirts',
        ),
        migrations.DeleteModel(
            name='MalePants',
        ),
        migrations.DeleteModel(
            name='MaleShirts',
        ),
    ]
