# Generated by Django 3.2.5 on 2022-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220515_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemalePants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('tummy_shape', models.CharField(max_length=20)),
                ('fit_preference', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('waist_lower', models.IntegerField()),
                ('waist_top', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShirts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('tummy_shape', models.CharField(max_length=20)),
                ('fit_preference', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('chest_lower', models.IntegerField()),
                ('chest_top', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MalePants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('tummy_shape', models.CharField(max_length=20)),
                ('fit_preference', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('waist_lower', models.IntegerField()),
                ('waist_top', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaleShirts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('tummy_shape', models.CharField(max_length=20)),
                ('fit_preference', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('chest_lower', models.IntegerField()),
                ('chest_top', models.IntegerField()),
            ],
        ),
    ]
