# Generated by Django 3.2.5 on 2022-05-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_femalepants_femaleshirts_malepants_maleshirts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormTable',
        ),
    ]
