# Generated by Django 3.2.5 on 2022-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_normtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=5)),
                ('item', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('age', models.FloatField()),
                ('height', models.FloatField()),
                ('chest_lower', models.FloatField()),
                ('chest_top', models.FloatField()),
                ('waist_lower', models.FloatField()),
                ('waist_top', models.FloatField()),
                ('brand_ASOS', models.FloatField()),
                ('brand_HM', models.FloatField()),
                ('brand_PULL_BEAR', models.FloatField()),
                ('brand_ZARA', models.FloatField()),
                ('size_labels', models.FloatField()),
                ('fit_labels', models.FloatField()),
                ('tummy_labels', models.FloatField()),
            ],
        ),
    ]
