# Generated by Django 3.2.5 on 2022-05-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220521_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StdTable',
        ),
    ]
